export const BUTTON = 'Asignar valores por defecto a formulario';
export const ERROR = 'Ha ocurrido un error al intentar guardar al usuario';
export const CLOSE = 'Cerrar';
export const USER = 'El usuario';
export const SUCCESS = 'se ha guardado de forma exitosa';
export const LOADING = 'Cargando...';
export const ONLINE = 'Conectado';
export const OFFLINE = 'Sin conexión';
export const CONNECTION = 'debido a una falla de conexión'